menu:
  Home: "/"
  "How to get it ?": "/How-to-get-it"
  Archives: /archives
  Wiki: https://github.com/kane-thornwyrd/Stranded-Strained/wiki
  Issues: https://github.com/kane-thornwyrd/Stranded-Strained/issues
  Sources: https://github.com/kane-thornwyrd/Stranded-Strained

addthis:
  enable: true
  pubid: kanethornwyrd

fancybox: false
backstretch: true
backstretchDuration: 15000
backstretchFade: 1000
google_analytics:
rss: rss.xml
